# Image name: test-run/net-services

FROM test-run/base:latest

RUN apt-get update && apt-get install -y python3 python3-pip

COPY test/net_services/test_net_services test_net_services
RUN chmod u+x test_net_services

ENTRYPOINT ["./test_net_services"]
